name: Publish bacon NuGet package

on:
  push:
    branches:  
    - master
    paths:
    - 'nuget-bacon/*'
    - '.github/workflows/nuget-bacon.yml'

jobs:
  build:
    name: Publish bacon NuGet package on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # windows-latest, 
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: infin8x/setup-dotnet@master 
      with:
        dotnet-version: 3.0.100
        source-url: https://nuget.pkg.github.com
        # config-file: nuget-bacon\nuget.config
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Testing
      run: cat /home/runner/work/nuget.config
    - name: Restore packages
      run: dotnet restore -v d nuget-bacon\
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - name: Create the package
      run: dotnet pack --configuration Release nuget-bacon\
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - name: Publish the package
      run: dotnet nuget push nuget-bacon/bin/Release/*.nupkg
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
