name: Publish ruby-bacon gem

on:
  push:
    branches:
    - master
    paths:
    - 'ruby-bacon/*'
    - '.github/workflows/ruby-bacon.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.x
    - name: Add GPR token to template credentials file
      run: sed -i -e 's/TOKEN/'$GITHUB_TOKEN'/g' ruby-bacon/credentials
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Create the gem
      run: gem build ruby-bacon/ruby-bacon.Gemspec
    - name: Publish the package
      run: gem push ruby-bacon/*.gem --key github --host https://rubygems.pkg.github.com/infin8x --config-file ruby-bacon/credentials
